### PR TITLE
Fix getting homedir on linux

### LINKED ISSUE #5: failed to get current user: user: Current not implemented on linux/amd64
I get an error when trying to run stern inside the Debian Docker container where I do most of my development. I assume I'm missing some dependency, but no idea which:

```
# wget https://github.com/wercker/stern/releases/download/1.0.0/stern_linux_amd64
# chmod +x stern_linux_amd64
# ./stern_linux_amd64 mypod
2016/10/31 10:45:12 failed to get current user: user: Current not implemented on linux/amd64
```

### PR DESCRIPTION
**Pull request by akupila**
Resolves an issue where the homedir could not be fetched correctly when the binary was not compiled on linux. 

This is done by using [go-homedir](github.com/mitchellh/go-homedir) which doesn't require cgo

Ref: https://stackoverflow.com/questions/20609415/cross-compiling-user-current-not-implemented-on-linux-amd64

fixes #5 

tested with:

```
docker run -it debian:jessie /bin/bash

# Download artifacts from https://app.wercker.com/wercker/stern/runs/build/58f71e4f7314290001d9b93a?step=58f71e69285d5d0001ace051
ARTIFACT=https://app.wercker.com/api/v3/runsteps/58f71e69285d5d0001ace051/artifacts
apt-get update && apt-get install wget -y
wget -O stern.tar $ARTIFACT
tar -xf stern.tar
cd artifacts
chmod +x stern
./stern mypod # ok
```

### CODE REVIEW

File: cmd/cli.go [hunk 1]
```diff
@@ -198,12 +198,12 @@ func getKubeConfig() (string, error) {
 	}
 
 	// kubernetes requires an absolute path
-	u, err := user.Current()
+	home, err := homedir.Dir()
 	if err != nil {
-		return "", errors.Wrap(err, "failed to get current user")
+		return "", errors.Wrap(err, "failed to get user homedir")
```
Comment (kokaz) [inline cmd/cli.go]: May I suggest `s/homedir/home directory/` ? which I think is more explicit

**Comment by jwolski2** [comment]
lgtm
